baseURL = "https://ybbond.dev/"
languageCode = "en-us"
title = "YBBond"

[permalinks]
  posts = "/posts/:year-:month-:title/"

[params]
  author = "Yohanes Bandung Bondowoso"
  description = "Thoughts, ideas and writings of me, Yohanes Bandung."
  mainSiteURL = "https://ybbond.dev"
  email = "bandungpenting@gmail.com"
  twitter = "bandungpenting"
  github = "ybbond"
  microblog = "ybbond"

[markup.goldmark.renderer]
    hardWraps = true
    unsafe = true
    xhtml = true

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 8
[[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv"
    weight = 9
[[menu.main]]
    identifier = "uses"
    name = "Uses"
    url = "/uses"
    weight = 10
