baseURL = "https://blog.ybbond.dev"
languageCode = "en-us"
title = "YBBond Blog"
theme = "hudown"

[markup.goldmark.renderer]
    hardWraps = true
    unsafe = true
    xhtml = true

[params]
    author = "Yohanes Bandung Bondowoso"
    description = "Thoughts, ideas and writings of me, Yohanes Bandung. My other site: https://ybbond.dev/"
    mainSiteURL = "https://ybbond.dev"
    email = "bandungpenting@gmail.com"
    twitter = "bandungpenting"
    github = "ybbond"
    themeColor = "#333333"
    ampElements = ["amp-analytics", "amp-social-share", "amp-install-serviceworker", "amp-iframe"]

# Menu elements
[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 8
[[menu.main]]
    identifier = "Uses"
    name = "Uses"
    url = "/uses"
    weight = 9
[[menu.main]]
    identifier = "author"
    name = "My Site"
    url = "https://ybbond.dev/"
    weight = 10