baseURL = "https://blog.ybbond.dev"
languageCode = "en-us"
title = "YBBond Blog"
theme = "hudown"

# Menu elements
[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 8
[[menu.main]]
    identifier = "author"
    name = "My Site"
    url = "https://ybbond.dev/"
    weight = 9
[[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 10

[params]
    themeColor = "#333333"
    ampElements = ["amp-analytics", "amp-social-share", "amp-install-serviceworker", "amp-iframe"]
